import pandas as pd
import glob
import os

def remove_fecha_columns():
    # 1. Find the folder where this script is located
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # 2. Look for all .csv files in that folder
    csv_files = glob.glob(os.path.join(script_dir, "*.csv"))
    
    if not csv_files:
        print("❌ No CSV files found.")
        return

    print(f"✅ Found {len(csv_files)} CSV files. Cleaning columns...\n")

    files_cleaned = 0

    for file_path in csv_files:
        filename = os.path.basename(file_path)
        
        # Skip files we've already cleaned to prevent duplication
        if filename.startswith("Cleaned_"):
            continue

        try:
            # 3. Read the CSV
            # encoding='utf-8-sig' ensures accents/tildes are handled correctly
            df = pd.read_csv(file_path, encoding='utf-8-sig')
            
            # 4. Filter columns
            # Keep columns that are NOT named "Fecha" or "Fecha.1", "Fecha.2", etc.
            # We explicitly KEEP "Fecha-Hora de Inicio" and "Fecha-Hora de Fin"
            # because they don't exactly match the string "Fecha" or "Fecha." pattern check below
            
            columns_to_keep = []
            for col in df.columns:
                # Logic: drop if exact match "Fecha" OR starts with "Fecha." (generated by pandas for duplicates)
                if col == "Fecha" or col.startswith("Fecha."):
                    continue
                columns_to_keep.append(col)
            
            # Create new dataframe with only the desired columns
            df_clean = df[columns_to_keep]
            
            # 5. Save as a new file (so we don't delete your original data)
            new_filename = f"Cleaned_{filename}"
            output_path = os.path.join(script_dir, new_filename)
            
            df_clean.to_csv(output_path, index=False, sep=',', encoding='utf-8-sig')
            
            print(f"[OK] Created: {new_filename}")
            files_cleaned += 1
            
        except Exception as e:
            print(f"❌ Error cleaning {filename}: {e}")

    print("\n" + "="*30)
    print(f"🎉 Success! Cleaned {files_cleaned} files.")
    print("="*30)

if __name__ == "__main__":
    remove_fecha_columns()